brew "vim"  # https://www.vim.org/

brew "bash"             # https://www.gnu.org/software/bash/bash.html
brew "bash-completion"  # https://salsa.debian.org/debian/bash-completion

brew "rename"     # http://plasmasturm.org/code/rename
brew "tree"       # https://github.com/Old-Man-Programmer/tree
brew "wget"       # https://www.gnu.org/software/wget/wget.html
brew "eza"        # https://github.com/eza-community/eza
brew "fd"         # https://github.com/sharkdp/fd
brew "rg"         # https://github.com/BurntSushi/ripgrep
brew "zoxide"     # https://github.com/ajeetdsouza/zoxide
brew "tig"        # https://github.com/jonas/tig
brew "bat"        # https://github.com/sharkdp/bat
brew "fpp"        # https://github.com/facebook/PathPicker
brew "ghq"        # https://github.com/x-motemen/ghq
brew "fzf"        # https://github.com/junegunn/fzf
brew "starship"   # https://github.com/starship/starship
brew "rlwrap"     # https://github.com/hanslub42/rlwrap
brew "coreutils"  # https://www.gnu.org/software/coreutils/
brew "grep"       # https://www.gnu.org/software/grep/
brew "gawk"       # https://www.gnu.org/software/gawk/
brew "gzip"       # https://www.gnu.org/software/gzip/
brew "gnu-tar"    # https://www.gnu.org/software/tar/
brew "gnu-sed"    # https://www.gnu.org/software/sed/
brew "gnu-time"   # https://www.gnu.org/software/time/

brew "git"        # https://git-scm.com/
brew "git-delta"  # https://github.com/dandavison/delta
brew "git-lfs"    # https://git-lfs.com/

brew "tmux"                       # https://tmux.github.io/
brew "reattach-to-user-namespace" # https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
brew "urlview"                    # https://packages.debian.org/sid/misc/urlview

brew "gh"             # https://cli.github.com/
brew "gpg2"           # https://gnupg.org/
brew "pinentry-mac"   # https://github.com/GPGTools/pinentry

brew "colima" # https://github.com/abiosoft/colima

brew "asdf" # https://asdf-vm.com/

brew "glow" # https://github.com/charmbracelet/glow
